CREATE TABLE target.dim_activity_type (
    activity_type_key NUMBER GENERATED BY DEFAULT AS IDENTITY,
    activity_code VARCHAR2(30) NOT NULL,
    activity_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),

    CONSTRAINT pk_dim_activity_type
        PRIMARY KEY (activity_type_key),

    CONSTRAINT uq_dim_activity_type_code
        UNIQUE (activity_code)
);