-- DIM_EMPLOYEE, DIM_PROJECT si DIM_TRAINING vor fi create de colegi.
-- De aceea, momentan exista FK doar catre DIM_DATE si DIM_ACTIVITY_TYPE.

CREATE TABLE target.fact_employee_activity (
    activity_key NUMBER GENERATED BY DEFAULT AS IDENTITY,

    employee_key NUMBER NOT NULL,
    date_key NUMBER NOT NULL,
    activity_type_key NUMBER NOT NULL,

    project_key NUMBER,
    training_key NUMBER,

    source_system VARCHAR2(50) NOT NULL,
    source_record_id VARCHAR2(100) NOT NULL,
    hours NUMBER(5,2) NOT NULL,

    load_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    etl_run_id NUMBER NOT NULL,

    CONSTRAINT pk_fact_employee_activity
        PRIMARY KEY (activity_key),

    CONSTRAINT fk_fact_date
        FOREIGN KEY (date_key)
        REFERENCES target.dim_date(date_key),

    CONSTRAINT fk_fact_activity
        FOREIGN KEY (activity_type_key)
        REFERENCES target.dim_activity_type(activity_type_key),

    CONSTRAINT ck_fact_activity_hours
        CHECK (hours >= 0),

    CONSTRAINT uq_fact_activity_source
        UNIQUE (
            source_system,
            source_record_id,
            activity_type_key
        )
);