/*
===============================================================================
Story:       US-13
Purpose:     Create typed and validated training staging tables.
Execution:   Run as SYSTEM.
===============================================================================
*/

CREATE TABLE staging.stg_training_session (
    session_stage_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    session_raw_id NUMBER NOT NULL,
    run_id NUMBER NOT NULL,
    session_source_key VARCHAR2(64) NOT NULL,

    meeting_title VARCHAR2(500),
    reported_participant_count NUMBER,

    start_timestamp TIMESTAMP,
    end_timestamp TIMESTAMP,
    meeting_duration_seconds NUMBER,
    average_attendance_seconds NUMBER,

    validation_status VARCHAR2(20) NOT NULL,
    validation_message VARCHAR2(4000),
    process_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_stg_training_session
        PRIMARY KEY (session_stage_id),

    CONSTRAINT uq_stg_training_session_raw
        UNIQUE (session_raw_id),

    CONSTRAINT ck_stg_training_session_status
        CHECK (validation_status IN ('VALID', 'INVALID'))
);


CREATE TABLE staging.stg_training_participant (
    participant_stage_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    participant_raw_id NUMBER NOT NULL,
    session_raw_id NUMBER NOT NULL,
    run_id NUMBER NOT NULL,

    participant_name VARCHAR2(300),
    email VARCHAR2(320),
    participant_id VARCHAR2(500),
    participant_role VARCHAR2(100),

    first_join_timestamp TIMESTAMP,
    last_leave_timestamp TIMESTAMP,
    duration_seconds NUMBER,

    validation_status VARCHAR2(20) NOT NULL,
    validation_message VARCHAR2(4000),
    process_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_stg_training_participant
        PRIMARY KEY (participant_stage_id),

    CONSTRAINT uq_stg_training_participant_raw
        UNIQUE (participant_raw_id),

    CONSTRAINT ck_stg_training_part_status
        CHECK (validation_status IN ('VALID', 'INVALID'))
);


CREATE TABLE staging.stg_training_activity (
    activity_stage_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    activity_raw_id NUMBER NOT NULL,
    session_raw_id NUMBER NOT NULL,
    run_id NUMBER NOT NULL,

    participant_name VARCHAR2(300),
    email VARCHAR2(320),
    participant_id VARCHAR2(500),
    participant_role VARCHAR2(100),

    join_timestamp TIMESTAMP,
    leave_timestamp TIMESTAMP,
    duration_seconds NUMBER,

    validation_status VARCHAR2(20) NOT NULL,
    validation_message VARCHAR2(4000),
    process_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_stg_training_activity
        PRIMARY KEY (activity_stage_id),

    CONSTRAINT uq_stg_training_activity_raw
        UNIQUE (activity_raw_id),

    CONSTRAINT ck_stg_training_activity_status
        CHECK (validation_status IN ('VALID', 'INVALID'))
);


GRANT SELECT ON sources.training_session_raw TO staging;
GRANT SELECT ON sources.training_participant_raw TO staging;
GRANT SELECT ON sources.training_activity_raw TO staging;

GRANT EXECUTE ON etl_control.pkg_etl_audit TO staging;

GRANT INSERT, DELETE
ON etl_control.etl_error_log
TO staging;

GRANT DELETE
ON etl_control.data_quality_result
TO staging;