/*
===============================================================================
Story:       US-13
Purpose:     Create raw tables for Microsoft Teams meeting exports.
Execution:   Run as SYSTEM on FREEPDB1.
===============================================================================
*/

CREATE TABLE sources.training_session_raw (
    session_raw_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    session_source_key VARCHAR2(64) NOT NULL,
    run_id NUMBER NOT NULL,

    dataset_name VARCHAR2(100) DEFAULT 'TRAINING_ATTENDANCE' NOT NULL,
    source_file_name VARCHAR2(255) NOT NULL,
    source_file_hash VARCHAR2(64) NOT NULL,

    meeting_title_raw VARCHAR2(500),
    attended_participants_raw VARCHAR2(100),
    start_time_raw VARCHAR2(100),
    end_time_raw VARCHAR2(100),
    meeting_duration_raw VARCHAR2(100),
    average_attendance_time_raw VARCHAR2(100),

    process_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_training_session_raw
        PRIMARY KEY (session_raw_id),

    CONSTRAINT uq_training_session_source_key
        UNIQUE (session_source_key),

    CONSTRAINT uq_training_session_file_hash
        UNIQUE (source_file_hash)
);


CREATE TABLE sources.training_participant_raw (
    participant_raw_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    session_raw_id NUMBER NOT NULL,
    run_id NUMBER NOT NULL,

    dataset_name VARCHAR2(100) DEFAULT 'TRAINING_ATTENDANCE' NOT NULL,
    source_file_name VARCHAR2(255) NOT NULL,
    source_row_number NUMBER NOT NULL,

    participant_name_raw VARCHAR2(300),
    first_join_raw VARCHAR2(100),
    last_leave_raw VARCHAR2(100),
    in_meeting_duration_raw VARCHAR2(100),
    email_raw VARCHAR2(320),
    participant_id_raw VARCHAR2(500),
    role_raw VARCHAR2(100),

    raw_record CLOB,
    process_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_training_participant_raw
        PRIMARY KEY (participant_raw_id),

    CONSTRAINT fk_training_participant_session
        FOREIGN KEY (session_raw_id)
        REFERENCES sources.training_session_raw(session_raw_id),

    CONSTRAINT uq_training_participant_source
        UNIQUE (session_raw_id, source_row_number)
);


CREATE TABLE sources.training_activity_raw (
    activity_raw_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    session_raw_id NUMBER NOT NULL,
    run_id NUMBER NOT NULL,

    dataset_name VARCHAR2(100) DEFAULT 'TRAINING_ATTENDANCE' NOT NULL,
    source_file_name VARCHAR2(255) NOT NULL,
    source_row_number NUMBER NOT NULL,

    participant_name_raw VARCHAR2(300),
    join_time_raw VARCHAR2(100),
    leave_time_raw VARCHAR2(100),
    duration_raw VARCHAR2(100),
    email_raw VARCHAR2(320),
    participant_id_raw VARCHAR2(500),
    role_raw VARCHAR2(100),

    raw_record CLOB,
    process_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_training_activity_raw
        PRIMARY KEY (activity_raw_id),

    CONSTRAINT fk_training_activity_session
        FOREIGN KEY (session_raw_id)
        REFERENCES sources.training_session_raw(session_raw_id),

    CONSTRAINT uq_training_activity_source
        UNIQUE (session_raw_id, source_row_number)
);


CREATE INDEX sources.idx_training_participant_email
    ON sources.training_participant_raw(email_raw);

CREATE INDEX sources.idx_training_participant_id
    ON sources.training_participant_raw(participant_id_raw);

CREATE INDEX sources.idx_training_activity_email
    ON sources.training_activity_raw(email_raw);


GRANT EXECUTE ON etl_control.pkg_etl_audit TO sources;