CREATE TABLE target.dim_project
(
    project_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    project_code VARCHAR2(100 CHAR) NOT NULL,

    dataset_name VARCHAR2(100 CHAR) NOT NULL,

    process_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_dim_project
        PRIMARY KEY (project_key),

    CONSTRAINT uq_dim_project
        UNIQUE (project_code)
);

INSERT INTO target.dim_project
(
    project_key,
    project_code,
    dataset_name
)
VALUES
(
    0,
    'UNKNOWN',
    'SYSTEM'
);

COMMIT;