CREATE TABLE target.dim_employee
(
    employee_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    employee_id VARCHAR2(255 CHAR) NOT NULL,

    employee_name VARCHAR2(255 CHAR) NOT NULL,

    grade VARCHAR2(100 CHAR) NOT NULL,

    discipline VARCHAR2(100 CHAR) NOT NULL,

    line_manager VARCHAR2(255 CHAR) NOT NULL,

    delivery_unit VARCHAR2(100 CHAR) NOT NULL,

    dataset_name VARCHAR2(100 CHAR) NOT NULL,

    process_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_dim_employee
        PRIMARY KEY (employee_key),

    CONSTRAINT uq_dim_employee
        UNIQUE (employee_id)
);

INSERT INTO target.dim_employee
(
    employee_key,
    employee_id,
    employee_name,
    grade,
    discipline,
    line_manager,
    delivery_unit,
    dataset_name
)
VALUES
(
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'SYSTEM'
);

COMMIT;