CREATE TABLE target.dim_employee
(
    employee_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
 
    employee_id VARCHAR2(320 CHAR) NOT NULL,
 
    employee_name VARCHAR2(300 CHAR),
 
    dataset_name VARCHAR2(100 CHAR) NOT NULL,
 
    process_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP,
 
    CONSTRAINT pk_dim_employee
        PRIMARY KEY (employee_key),
 
    CONSTRAINT uq_dim_employee
        UNIQUE (employee_id)
);
 
INSERT INTO target.dim_employee
(
    employee_key,
    employee_id,
    employee_name,
    dataset_name
)
VALUES
(
    0,
    'UNKNOWN',
    'Unknown Employee',
    'SYSTEM'
);
 
COMMIT;