/*
===============================================================================
Story:       US-07
Purpose:     Create raw table for Worked Hours dataset.
Execution:   Run as SOURCES on FREEPDB1.
===============================================================================
*/

CREATE TABLE worked_hours_raw (

    worked_hours_raw_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    run_id NUMBER NOT NULL,

    dataset_name VARCHAR2(100)
        DEFAULT 'WORKED_HOURS'
        NOT NULL,

    source_file_name VARCHAR2(255)
        NOT NULL,

    source_row_number NUMBER
        NOT NULL,

    name_raw VARCHAR2(300),

    email_raw VARCHAR2(320),

    date_worked_raw VARCHAR2(100),

    worked_hours_raw VARCHAR2(100),

    project_code_raw VARCHAR2(100),

    raw_record CLOB,

    process_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP
        NOT NULL,

    CONSTRAINT pk_worked_hours_raw
        PRIMARY KEY (worked_hours_raw_id),

    CONSTRAINT uq_worked_hours_source
        UNIQUE (
            source_file_name,
            source_row_number
        )
);

--CREATE INDEX idx_worked_hours_email
--ON worked_hours_raw(employee_email_raw);

--CREATE INDEX idx_worked_hours_project
--ON worked_hours_raw(project_code_raw);

