
CREATE TABLE sources.timesheet_absence_raw (
    timesheet_absence_raw_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    run_id NUMBER NOT NULL,
    dataset_name VARCHAR2(100)
        DEFAULT 'TIMESHEET_ABSENCES' NOT NULL,
    source_file_name VARCHAR2(255) NOT NULL,
    source_file_hash VARCHAR2(64) NOT NULL,
    source_row_number NUMBER NOT NULL,

    name_raw VARCHAR2(300),
    email_raw VARCHAR2(320),
    date_worked_raw VARCHAR2(100),
    absence_hours_raw VARCHAR2(100),
    project_code_raw VARCHAR2(100),

    raw_record CLOB,
    process_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_timesheet_absence_raw
        PRIMARY KEY (timesheet_absence_raw_id),

    CONSTRAINT uq_timesheet_absence_source_row
        UNIQUE (source_file_hash, source_row_number)
);

CREATE INDEX sources.idx_ts_absence_email_raw
    ON sources.timesheet_absence_raw(email_raw);

GRANT SELECT ON sources.timesheet_absence_raw TO staging;
GRANT EXECUTE ON etl_control.pkg_etl_audit TO sources;
