CREATE TABLE etl_control.etl_run (
    run_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pipeline_name VARCHAR2(100) NOT NULL,
    source_name VARCHAR2(100),
    start_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'RUNNING' NOT NULL,
    rows_read NUMBER DEFAULT 0 NOT NULL,
    rows_loaded NUMBER DEFAULT 0 NOT NULL,
    rows_rejected NUMBER DEFAULT 0 NOT NULL,
    error_message VARCHAR2(4000),

    CONSTRAINT pk_etl_run
        PRIMARY KEY (run_id),

    CONSTRAINT ck_etl_run_status
        CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED'))
);