CREATE TABLE etl_control.etl_error_log (
    error_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    run_id NUMBER,
    pipeline_name VARCHAR2(100),
    source_name VARCHAR2(100),
    source_row_number NUMBER,
    error_code VARCHAR2(100),
    error_message VARCHAR2(4000) NOT NULL,
    raw_record CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_etl_error_log
        PRIMARY KEY (error_id),

    CONSTRAINT fk_etl_error_log_run
        FOREIGN KEY (run_id)
        REFERENCES etl_control.etl_run(run_id)
);