
CREATE TABLE staging.stg_timesheet_absence (
    timesheet_absence_stage_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    timesheet_absence_raw_id NUMBER NOT NULL,
    run_id NUMBER NOT NULL,

    employee_name VARCHAR2(300),
    employee_id_raw VARCHAR2(320),
    activity_date DATE,
    absence_hours NUMBER(5,2),
    project_code VARCHAR2(100),

    absence_type_code VARCHAR2(30) NOT NULL,

    validation_status VARCHAR2(20) NOT NULL,
    validation_message VARCHAR2(4000),
    process_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_stg_timesheet_absence
        PRIMARY KEY (timesheet_absence_stage_id),

    CONSTRAINT uq_stg_timesheet_absence_raw
        UNIQUE (timesheet_absence_raw_id),

    CONSTRAINT ck_stg_timesheet_abs_status
        CHECK (validation_status IN ('VALID', 'INVALID')),

    CONSTRAINT ck_stg_timesheet_abs_type
        CHECK (
            absence_type_code IN (
                'ANNUAL_LEAVE',
                'SICK_LEAVE',
                'PUBLIC_HOLIDAY',
                'OTHER_ABSENCE'
            )
        )
);

GRANT EXECUTE ON etl_control.pkg_etl_audit TO staging;
GRANT INSERT, DELETE ON etl_control.etl_error_log TO staging;
GRANT DELETE ON etl_control.data_quality_result TO staging;

GRANT SELECT ON staging.stg_timesheet_absence TO sources;
