CREATE TABLE target.dim_training (
    training_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    training_source_key VARCHAR2(64) NOT NULL,
    training_name VARCHAR2(500) NOT NULL,

    session_start_timestamp TIMESTAMP,
    session_end_timestamp TIMESTAMP,
    reported_participant_count NUMBER,

    source_system VARCHAR2(100) NOT NULL,
    source_record_id VARCHAR2(100) NOT NULL,

    load_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dim_training
        PRIMARY KEY (training_key),

    CONSTRAINT uq_dim_training_source_key
        UNIQUE (training_source_key)
);

GRANT SELECT
ON staging.stg_training_session
TO target;