CREATE TABLE staging.stg_employee
(
    stg_employee_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    employee_id VARCHAR2(255 CHAR) NOT NULL,

    employee_name VARCHAR2(255 CHAR) NOT NULL,

    grade VARCHAR2(100 CHAR) NOT NULL,

    discipline VARCHAR2(100 CHAR) NOT NULL,

    line_manager VARCHAR2(255 CHAR) NOT NULL,

    delivery_unit VARCHAR2(100 CHAR) NOT NULL,

    validation_status VARCHAR2(20 CHAR),

    validation_message VARCHAR2(500 CHAR),

    dataset_name VARCHAR2(100 CHAR) NOT NULL,

    source_file_name VARCHAR2(255 CHAR) NOT NULL,

    process_timestamp TIMESTAMP,

    CONSTRAINT pk_stg_employee
        PRIMARY KEY (stg_employee_key)
);