CREATE TABLE sources.exam_absence_raw (
    exam_absence_raw_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    run_id NUMBER NOT NULL,
    dataset_name VARCHAR2(100) NOT NULL,
    employee_id_raw VARCHAR2(255),
    activity_date_raw VARCHAR2(100),
    activity_code_raw VARCHAR2(100),
    source_file_name VARCHAR2(255) NOT NULL,
    source_file_hash VARCHAR2(64) NOT NULL,
    source_row_number NUMBER,
    source_column_name VARCHAR2(255),
    raw_record CLOB,
    process_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_exam_absence_raw PRIMARY KEY (exam_absence_raw_id),
    CONSTRAINT uq_exam_absence_raw_origin UNIQUE (
        source_file_hash,
        source_row_number,
        source_column_name
    )
);
