CREATE TABLE sources.employee_master_raw
(
    raw_employee_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    employee_id VARCHAR2(255 CHAR) NOT NULL,

    employee_name VARCHAR2(255 CHAR) NOT NULL,

    grade VARCHAR2(100 CHAR) NOT NULL,

    discipline VARCHAR2(100 CHAR) NOT NULL,

    line_manager VARCHAR2(255 CHAR) NOT NULL,

    delivery_unit VARCHAR2(100 CHAR) NOT NULL,

    dataset_name VARCHAR2(100 CHAR) NOT NULL,

    source_file_name VARCHAR2(255 CHAR) NOT NULL,

    process_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_employee_master_raw
        PRIMARY KEY (raw_employee_key)
);