CREATE TABLE staging.stg_exam_absence (
    exam_absence_stage_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    exam_absence_raw_id NUMBER NOT NULL,
    run_id NUMBER NOT NULL,
    employee_id_raw VARCHAR2(255) NOT NULL,
    activity_date DATE NOT NULL,
    activity_code VARCHAR2(100) NOT NULL,
    source_file_name VARCHAR2(255) NOT NULL,
    source_row_number NUMBER,
    source_column_name VARCHAR2(255),
    validation_status VARCHAR2(20) DEFAULT 'VALID' NOT NULL,
    process_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_stg_exam_absence PRIMARY KEY (exam_absence_stage_id),
    CONSTRAINT ck_stg_exam_absence_status CHECK (validation_status IN ('VALID')),
    CONSTRAINT uq_stg_exam_absence_activity UNIQUE (
        run_id,
        employee_id_raw,
        activity_date,
        activity_code
    )
);
